[package]
name = "py-rusty-logger"
version = { workspace = true }
edition = "2021"

[lib]
name = "py_rusty_logger"
crate-type = ["cdylib", "rlib"]

[dependencies]
rusty-logging = { workspace = true }
pyo3 = { workspace = true }
