comment: false

coverage:
  status:
    project:
      default: false
      app:
        paths: "!tests/"
        target: 80%
        threshold: 10% 
        if_ci_failed: error #success, failure, error, ignore


