comment: false

coverage:
  range: "70...100"
  status:
    project:
      default:
        target: 80
        paths:
          - "!tests/"
        threshold: 10% 
        if_ci_failed: error #success, failure, error, ignore


