[workspace]
dependencies_update = true
changelog_update = true
pr_labels = ["release"]
semver_check = true
publish_timeout = "10m" # set a timeout for `cargo publish`
git_tag_enable = false
git_release_enable = false
publish = true
repo_url = "https://github.com/demml/rusty-logger"

[[package]]
name = "py-rusty-logger"
publish = false