name: 'ðŸž Bug report - Python'
description: Report an issue with Python Rusty-Logger.
labels: [bug, python]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: >
            I have checked that this issue has not already been reported.
          required: true
        - label: >
            I have confirmed this bug exists on the
            [latest version](https://pypi.org/project/rusty-logger/) of Rusty Logger.
          required: true

  - type: textarea
    id: example
    attributes:
      label: Reproducible example
      description: >
        Please follow [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) on how to
        provide a minimal, copy-pastable example. Include the (wrong) output if applicable.
      value: |
        ```python

        ```
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: >
        Provide any relevant log output or stack trace.
      render: shell

  - type: textarea
    id: problem
    attributes:
      label: Issue description
      description: >
        Provide any additional information you think might be relevant.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: >
        Describe or show a code example of the expected behavior.
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Installed versions
      description: >
        Paste the output of ``pl.show_versions()``
      value: |
        <details>

        ```
        Replace this line with the output of rusty_logger.version().
        ```

        </details>
    validations:
      required: true