from typing import Any, Optional

class JsonLogger:
    @classmethod
    def get_logger(cls, name: str, output: Optional[str] = None, level: Optional[str] = None) -> "JsonLogger": ...
    def info(self, message: str, **kwargs: Any) -> None: ...
    def debug(self, message: str, **kwargs: Any) -> None: ...
    def warning(self, message: str, **kwargs: Any) -> None: ...
    def error(self, message: str, **kwargs: Any) -> None: ...
